name: CI

on:
  push:
    branches:
      - '*'
  pull_request:
    branches:
      - '*'
    types:
      - opened
      - edited
      - synchronize
      - reopened
  workflow_dispatch:      

permissions:
  contents: read

concurrency:
  group: ${{ github.ref == 'refs/heads/trunk' && format('ci-main-{0}', github.sha) || format('ci-main-{0}', github.ref) }}
  cancel-in-progress: true

jobs:
  build:
    name: 'Java 8'
    runs-on: ubuntu-latest
    steps:
    - name: 'Checkout xalan-java'
      uses: actions/checkout@v3
      
    - name: 'Set up JDK 8'
      uses: actions/setup-java@v2
      with:
        distribution: zulu
        java-version: 8
        
    - name: 'Install dependencies to local Maven repo'
      run: |        
        mvn install:install-file \
          -Dfile=libs/Jlex/Jlex/1.0/jlex-1.0.jar \
          -DgroupId=Jlex \
          -DartifactId=Jlex \
          -Dversion=1.0 \
          -Dpackaging=jar \
          -DlocalRepositoryPath=libs \
          -DcreateChecksum=true
          
        mvn install:install-file \
          -Dfile=libs/edu/princeton/cs/java_cup/1.0/java_cup-1.0.jar \
          -DgroupId=edu.princeton.cs \
          -DartifactId=java_cup \
          -Dversion=1.0 \
          -Dpackaging=jar \
          -DlocalRepositoryPath=libs
          
        mvn install:install-file \
          -Dfile=libs/edu/princeton/cs/cup_runtime/1.0/cup_runtime-1.0.jar \
          -DgroupId=edu.princeton.cs \
          -DartifactId=cup_runtime \
          -Dversion=1.0 \
          -Dpackaging=jar \
          -DlocalRepositoryPath=libs
          
        mvn install:install-file \
          -Dfile=libs/org/apache/xsl/xpath31_types/1.0/xpath31_types-1.0.jar \
          -DgroupId=org.apache.xsl \
          -DartifactId=xpath31_types \
          -Dversion=1.0 \
          -Dpackaging=jar \
          -DlocalRepositoryPath=libs
          
        mvn install:install-file \
          -Dfile=libs/org/apache/xerces/xercesImpl/2.12.3/xercesImpl-2.12.3.jar \
          -DgroupId=org.apache.xerces \
          -DartifactId=xercesImpl \
          -Dversion=2.12.3 \
          -Dpackaging=jar \
          -DlocalRepositoryPath=libs
          
        mvn install:install-file \
          -Dfile=libs/org/apache/xerces/xml-apis/1.4.02/xml-apis-1.4.02.jar \
          -DgroupId=org.apache.xerces \
          -DartifactId=xml-apis \
          -Dversion=1.4.02 \
          -Dpackaging=jar \
          -DlocalRepositoryPath=libs
          
        mvn install:install-file \
          -Dfile=libs/org/apache/commons/bsf/1.0/bsf-1.0.jar \
          -DgroupId=org.apache.commons \
          -DartifactId=bsf \
          -Dversion=1.0 \
          -Dpackaging=jar \
          -DlocalRepositoryPath=libs
        
    - name: 'Build Xalan jars with local dependencies'
      run: |
        cat <<EOF > settings.xml
        <settings xmlns="http://maven.apache.org/SETTINGS/1.0.0"
          xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
          xsi:schemaLocation="http://maven.apache.org/SETTINGS/1.0.0
          https://maven.apache.org/xsd/settings-1.0.0.xsd">
          <localRepository>\${basedir}/libs</localRepository>
          <offline>true</offline>
          <mirrors>
            <mirror>
              <id>local-only</id>
              <name>Local Repository Only</name>
              <url>file://\${basedir}/libs</url>
              <mirrorOf>*</mirrorOf>
            </mirror>
          </mirrors>
          <profiles>
            <profile>
              <id>disable-central</id>
              <repositories>
                <repository>
                  <id>central</id>
                  <url>http://invalid.localhost</url>
                </repository>
              </repositories>
              <pluginRepositories>
                <pluginRepository>
                  <id>central</id>
                  <url>http://invalid.localhost</url>
                </pluginRepository>
              </pluginRepositories>
            </profile>
          </profiles>
          <activeProfiles>
            <activeProfile>disable-central</activeProfile>
          </activeProfiles>
        </settings>
        EOF
        
        mvn -s settings.xml clean install test \
          -Dtest=AllXalanXSLT3Tests \
          -Dmaven.repo.local=libs \
          -o \
          -B
        
    - name: Upload jar
      uses: actions/upload-artifact@v4
      with:
        name: upload-jar
        path: build/*jar
        
    - name: Upload lib
      uses: actions/upload-artifact@v4
      with:
        name: native-lib
        path: lib
