name: CI

on:
  push:
    branches:
      - '*'
  pull_request:
    branches:
      - '*'
    types:
      - opened
      - edited
      - synchronize
      - reopened
  workflow_dispatch:      

permissions:
  contents: read

concurrency:
  group: ${{ github.ref == 'refs/heads/trunk' && format('ci-main-{0}', github.sha) || format('ci-main-{0}', github.ref) }}
  cancel-in-progress: true

jobs:
  build:
    name: 'Java 8'
    runs-on: ubuntu-latest
    steps:
    - name: 'Checkout xalan-java'
      uses: actions/checkout@v3
      
    - name: 'Set up JDK 8'
      uses: actions/setup-java@v2
      with:
        distribution: zulu
        java-version: 8
        
    - name: 'Install dependencies directly from libs'
      run: |
        # 定义函数用于安装 JAR 文件
        install_jar() {
          local file=$1
          local groupId=$2
          local artifactId=$3
          local version=$4

          # 检查本地仓库中是否已存在该 artifact
          local artifactPath="libs/${groupId//.//}/${artifactId}/${version}/${artifactId}-${version}.jar"
          if [ ! -f "$artifactPath" ]; then
            echo "Installing $artifactId..."
            mvn install:install-file \
              -Dfile="$file" \
              -DgroupId="$groupId" \
              -DartifactId="$artifactId" \
              -Dversion="$version" \
              -Dpackaging=jar \
              -DlocalRepositoryPath=libs
          else
            echo "Skipping $artifactId, already installed."
          fi
        }

        # 确保 libs 目录存在
        mkdir -p libs

        # 调用函数安装所有依赖项
        install_jar "libs/JLex/JLex/1.0/jlex-1.0.jar" "Jlex" "Jlex" "1.0"
        install_jar "libs/edu/princeton/cs/java_cup/1.0/java_cup-1.0.jar" "edu.princeton.cs" "java_cup" "1.0"
        install_jar "libs/edu/princeton/cs/cup_runtime/1.0/cup_runtime-1.0.jar" "edu.princeton.cs" "cup_runtime" "1.0"
        install_jar "libs/org/apache/xsl/xpath31_types/1.0/xpath31_types-1.0.jar" "org.apache.xsl" "xpath31_types" "1.0"
        install_jar "libs/org/apache/xerces/xercesImpl/2.12.3/xercesImpl-2.12.3.jar" "org.apache.xerces" "xercesImpl" "2.12.3"
        install_jar "libs/org/apache/xerces/xml-apis/1.4.02/xml-apis-1.4.02.jar" "org.apache.xerces" "xml-apis" "1.4.02"
        install_jar "libs/org/apache/commons/bsf/1.0/bsf-1.0.jar" "org.apache.commons" "bsf" "1.0"
        
    - name: 'Build project'
      run: |
        # 运行Maven构建（在线模式）
        mvn clean install test \
          -Dtest=AllXalanXSLT3Tests \
          -Dmaven.repo.local=libs \
          -B
        
    - name: Upload jar
      uses: actions/upload-artifact@v4
      with:
        name: upload-jar
        path: build/*jar
        
    - name: Upload lib
      uses: actions/upload-artifact@v4
      with:
        name: native-lib
        path: lib
